apiVersion: v1
kind: Pod
metadata:
  name: sabor-total
  namespace: salsa
  annotations:
    student: "NOMBRE DEL ESTUDIANTE"
    music: "Salsa - Sabor Latino"
spec:
  containers:
    - name: salsero
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - latino
