apiVersion: v1
kind: Pod
metadata:
  name: rave-master
  namespace: techno
  annotations:
    student: "Juan Esteban Rodriguez"
    music: "Techno - Bass Boost"
spec:
  containers:
    - name: dj
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - electronico
