apiVersion: v1
kind: Pod
metadata:
  name: sabor-total-michaelramirez
  namespace: salsa
  annotations:
    student: "Michael Ramirez Suriel"
    music: "Salsa - Sabor Latino"
spec:
  containers:
    - name: salsero
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "sabor-latino"
      effect: "NoSchedule"
